name: Feature request
description: Suggest an idea for this project
title: "[Feature]: "
labels: [ "feature request" ]
body:
  - type: markdown
    attributes:
      value: |
        ## Suggesting a feature
        
        Thanks for taking the time to suggest a feature! Note that if I won't use the feature myself, I might not implement it myself either (as that is why this plugin exists at all :P). However, if you want to implement it yourself, I will gladly accept a pull request. Also note that I might take a while to respond, depending on how busy I am. Please be patient.
  - type: textarea
    attributes:
      label: Related problem
      description: Is your feature request related to a problem?
    validations:
      required: false
  - type: textarea
    attributes:
      label: My ideal solution
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Considered alternatives
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Intentions
      options:
        - label: I'm open to build this myself and PR it
          required: false
    validations:
      required: false
